services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
      dockerfile: src/main/resources/docker/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL}
      JWT_ISSUER: ${JWT_ISSUER}

      REFRESH_TTL: ${REFRESH_TTL}
      RESET_TTL: ${RESET_TTL}

      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${MAIL_FROM}

      FRONT_BASE_URL: ${FRONT_BASE_URL}

      SEED_ADMIN_ENABLED: ${SEED_ADMIN_ENABLED}
      SEED_ADMIN_EMAIL: ${SEED_ADMIN_EMAIL}
      SEED_ADMIN_USERNAME: ${SEED_ADMIN_USERNAME}
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD}

    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      - db

  front-auth:
    build:
      context: ./front-auth
      dockerfile: Dockerfile
    ports:
      - "${FRONT_PORT}:80"
    depends_on:
      - auth-service

volumes:
  auth_db_data:
